// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhgP8peZWoORNtV204yjf0h7MoQj5a9fo',
    appId: '1:1008642312089:web:1e67f343be37bde187b508',
    messagingSenderId: '1008642312089',
    projectId: 'my-readwise',
    authDomain: 'my-readwise.firebaseapp.com',
    storageBucket: 'my-readwise.appspot.com',
    measurementId: 'G-V8M31DYC6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtz9SE4crDNKn0BQQSDRIDuTQvXxFLjyY',
    appId: '1:1008642312089:android:e9cad9bb6934f9e087b508',
    messagingSenderId: '1008642312089',
    projectId: 'my-readwise',
    storageBucket: 'my-readwise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLCb6qCn78ljJ2rvEyQZq3IefEfQEIkIE',
    appId: '1:1008642312089:ios:5d60e47bb3ee6e2787b508',
    messagingSenderId: '1008642312089',
    projectId: 'my-readwise',
    storageBucket: 'my-readwise.appspot.com',
    iosBundleId: 'com.example.myReadwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLCb6qCn78ljJ2rvEyQZq3IefEfQEIkIE',
    appId: '1:1008642312089:ios:fdd8ae80933e92d587b508',
    messagingSenderId: '1008642312089',
    projectId: 'my-readwise',
    storageBucket: 'my-readwise.appspot.com',
    iosBundleId: 'com.example.myReadwise.RunnerTests',
  );
}
